### ISSUE TITLE
Towing when parked

### ISSUE THREAD

**Issue by vor777** [MaDHouSe79/qb-parkinglite#2]
Hey i was wondering if you could add in some functionality to account for if the parked vehicle is towed as currently when its taken away it just returns to the parked spot :) 

many thanks!!

**Comment by MaDHouSe79** [comment]
if you want that, you only need to unpark the vehicle when you want to tow it, use the unpark trigger for that ;)

`TriggerServerEvent('qb-parking:server:vehicle_action_unpark', QBCore.Functions.GetPlate(vehicle))`
