### ISSUE TITLE
Is still supported?

### ISSUE THREAD

**Issue by CarlBishop** [MaDHouSe79/qb-parkinglite#6]
Hi MadHouse.

Is this parkinglight still active?

I was looking for something similar, but seems to not work anymore on latest qbcore.

Car get parked, but just disappear, doesn't respawn.

**Comment by MaDHouSe79** [comment]
Hi, you can also use this one [mh-parking](https://github.com/MaDHouSe79/mh-parking)
its the same but with a few more options in it. :smile:

**Comment by CarlBishop** [comment]
Ok
